import type { Book, BorrowRecord, Category } from "@/lib/types";

/* Stable demo data so the app looks alive on first load. */

const now = () => new Date().toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();
const daysAhead = (n: number) => new Date(Date.now() + n * 86_400_000).toISOString();

export const seedCategories: Category[] = [
  { id: "cat-fiction",    name: "Fiction",     color: "#8B5CF6", created_at: now() },
  { id: "cat-nonfiction", name: "Non-fiction", color: "#06B6D4", created_at: now() },
  { id: "cat-science",    name: "Science",     color: "#10B981", created_at: now() },
  { id: "cat-bio",        name: "Biography",   color: "#F59E0B", created_at: now() },
  { id: "cat-selfhelp",   name: "Self-help",   color: "#EC4899", created_at: now() },
  { id: "cat-tech",       name: "Technology",  color: "#6366F1", created_at: now() },
];

export const seedBooks: Book[] = [
  {
    id: "book-1",
    title: "The Midnight Library",
    author: "Matt Haig",
    cover_url: null,
    isbn: "9780525559474",
    category_id: "cat-fiction",
    status: "reading",
    rating: 4,
    progress: 62,
    total_pages: 304,
    notes: "Beautiful exploration of regret and possibility.",
    added_at: daysAgo(42),
    updated_at: daysAgo(2),
  },
  {
    id: "book-2",
    title: "Atomic Habits",
    author: "James Clear",
    cover_url: null,
    isbn: "9780735211292",
    category_id: "cat-selfhelp",
    status: "completed",
    rating: 5,
    progress: 100,
    total_pages: 320,
    notes: "Re-read every quarter. The 1% better framing changed how I plan sprints.",
    added_at: daysAgo(120),
    updated_at: daysAgo(20),
  },
  {
    id: "book-3",
    title: "Project Hail Mary",
    author: "Andy Weir",
    cover_url: null,
    isbn: "9780593135204",
    category_id: "cat-fiction",
    status: "lent",
    rating: 5,
    progress: 100,
    total_pages: 496,
    notes: "Lent to Ayesha — she's been wanting hard sci-fi.",
    added_at: daysAgo(80),
    updated_at: daysAgo(7),
  },
  {
    id: "book-4",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    cover_url: null,
    isbn: "9780062316097",
    category_id: "cat-nonfiction",
    status: "reading",
    rating: 4,
    progress: 28,
    total_pages: 464,
    notes: "Dense but rewarding. Take notes per chapter.",
    added_at: daysAgo(15),
    updated_at: daysAgo(1),
  },
  {
    id: "book-5",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    cover_url: null,
    isbn: "9781449373320",
    category_id: "cat-tech",
    status: "reading",
    rating: 5,
    progress: 45,
    total_pages: 616,
    notes: "Chapter on replication is gold.",
    added_at: daysAgo(60),
    updated_at: daysAgo(3),
  },
  {
    id: "book-6",
    title: "Educated",
    author: "Tara Westover",
    cover_url: null,
    isbn: "9780399590504",
    category_id: "cat-bio",
    status: "completed",
    rating: 5,
    progress: 100,
    total_pages: 334,
    notes: null,
    added_at: daysAgo(200),
    updated_at: daysAgo(150),
  },
  {
    id: "book-7",
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    cover_url: null,
    isbn: "9780553380163",
    category_id: "cat-science",
    status: "wishlist",
    rating: null,
    progress: 0,
    total_pages: 256,
    notes: null,
    added_at: daysAgo(8),
    updated_at: daysAgo(8),
  },
  {
    id: "book-8",
    title: "The Pragmatic Programmer",
    author: "David Thomas, Andrew Hunt",
    cover_url: null,
    isbn: "9780135957059",
    category_id: "cat-tech",
    status: "lent",
    rating: 5,
    progress: 100,
    total_pages: 352,
    notes: "Lent to Bilal.",
    added_at: daysAgo(300),
    updated_at: daysAgo(35),
  },
  {
    id: "book-9",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    cover_url: null,
    isbn: "9780735219090",
    category_id: "cat-fiction",
    status: "wishlist",
    rating: null,
    progress: 0,
    total_pages: 384,
    notes: null,
    added_at: daysAgo(4),
    updated_at: daysAgo(4),
  },
];

export const seedBorrows: BorrowRecord[] = [
  {
    id: "borrow-1",
    book_id: "book-3",
    borrower_name: "Ayesha Khan",
    borrower_contact: "ayesha@example.com",
    lent_at: daysAgo(7),
    due_at: daysAhead(7),
    returned_at: null,
    notes: "She'll return after eid break.",
  },
  {
    id: "borrow-2",
    book_id: "book-8",
    borrower_name: "Bilal Ahmed",
    borrower_contact: "+92-300-1234567",
    lent_at: daysAgo(35),
    due_at: daysAgo(5),
    returned_at: null,
    notes: "OVERDUE — gentle reminder sent.",
  },
  {
    id: "borrow-3",
    book_id: "book-2",
    borrower_name: "Hira Sheikh",
    borrower_contact: null,
    lent_at: daysAgo(60),
    due_at: daysAgo(30),
    returned_at: daysAgo(25),
    notes: null,
  },
  {
    id: "borrow-4",
    book_id: "book-6",
    borrower_name: "Omar Farooq",
    borrower_contact: "omar@example.com",
    lent_at: daysAgo(150),
    due_at: daysAgo(120),
    returned_at: daysAgo(115),
    notes: null,
  },
];
